{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2023-41105",
	"modified": "2024-10-15T14:11:43Z",
	"published": "2023-08-23T07:15:00Z",
	"related": [
		"CVE-2023-41105",
		"USN-6547-1",
		"USN-6891-1"
	],
	"details": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "python3.11",
				"purl": "pkg:deb/ubuntu/python3.11?arch=src?distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.11.0~rc1-1~22.04"
			],
			"ecosystem_specific": {
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2023/UBUNTU-CVE-2023-41105.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:24.04:LTS",
				"name": "python3.12",
				"purl": "pkg:deb/ubuntu/python3.12?arch=src?distro=noble"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.12.0-6"
						}
					]
				}
			],
			"versions": [
				"3.12.0-1",
				"3.12.0-5"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "idle-python3.12",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12-dbg",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12-dev",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12-minimal",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12-stdlib",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "libpython3.12-testsuite",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-dbg",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-dev",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-doc",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-examples",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-full",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-minimal",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-nopie",
						"binary_version": "3.12.0-6"
					},
					{
						"binary_name": "python3.12-venv",
						"binary_version": "3.12.0-6"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2023/UBUNTU-CVE-2023-41105.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2023-41105"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/python/cpython/pull/107983"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-6547-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-41105"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-6891-1"
		}
	]
}
