{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2014-0480",
	"modified": "2014-08-26T00:00:00Z",
	"published": "2014-08-26T00:00:00Z",
	"related": [
		"CVE-2014-0480",
		"USN-2347-1"
	],
	"details": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated.",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:14.04:LTS",
				"name": "python-django",
				"purl": "pkg:deb/ubuntu/python-django?arch=src?distro=trusty"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.6.1-2ubuntu0.4"
						}
					]
				}
			],
			"versions": [
				"1.5.4-1ubuntu1",
				"1.6-1",
				"1.6.1-1",
				"1.6.1-2",
				"1.6.1-2ubuntu0.1",
				"1.6.1-2ubuntu0.2",
				"1.6.1-2ubuntu0.3"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-django",
						"binary_version": "1.6.1-2ubuntu0.4"
					},
					{
						"binary_name": "python-django-doc",
						"binary_version": "1.6.1-2ubuntu0.4"
					}
				],
				"ubuntu_priority": "low"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2014/UBUNTU-CVE-2014-0480.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2014-0480"
		},
		{
			"type": "REPORT",
			"url": "https://www.djangoproject.com/weblog/2014/aug/20/security/"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-2347-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2014-0480"
		}
	]
}
