{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2015-2317",
	"modified": "2015-03-19T00:00:00Z",
	"published": "2015-03-19T00:00:00Z",
	"related": [
		"CVE-2015-2317",
		"USN-2539-1"
	],
	"details": "The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x, 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly validate URLs, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a control character in a URL, as demonstrated by a \\x08javascript: URL.",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:14.04:LTS",
				"name": "python-django",
				"purl": "pkg:deb/ubuntu/python-django?arch=src?distro=trusty"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.6.1-2ubuntu0.8"
						}
					]
				}
			],
			"versions": [
				"1.5.4-1ubuntu1",
				"1.6-1",
				"1.6.1-1",
				"1.6.1-2",
				"1.6.1-2ubuntu0.1",
				"1.6.1-2ubuntu0.2",
				"1.6.1-2ubuntu0.3",
				"1.6.1-2ubuntu0.4",
				"1.6.1-2ubuntu0.5",
				"1.6.1-2ubuntu0.6"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-django",
						"binary_version": "1.6.1-2ubuntu0.8"
					},
					{
						"binary_name": "python-django-doc",
						"binary_version": "1.6.1-2ubuntu0.8"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2015/UBUNTU-CVE-2015-2317.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2015-2317"
		},
		{
			"type": "REPORT",
			"url": "https://www.djangoproject.com/weblog/2015/mar/18/security-releases/"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-2539-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2015-2317"
		}
	]
}
