{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2021-4041",
	"modified": "2022-08-24T16:15:00Z",
	"published": "2022-08-24T16:15:00Z",
	"related": [
		"CVE-2021-4041"
	],
	"details": "A flaw was found in ansible-runner. An improper escaping of the shell command, while calling the ansible_runner.interface.run_command, can lead to parameters getting executed as host's shell command. A developer could unintentionally write code that gets executed in the host rather than the virtual environment.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:22.04:LTS",
				"name": "ansible-runner",
				"purl": "pkg:deb/ubuntu/ansible-runner?arch=src?distro=jammy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.1.1-1"
						}
					]
				}
			],
			"versions": [
				"1.4.6-1",
				"1.4.6-1.1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-ansible-runner-doc",
						"binary_version": "2.1.1-1"
					},
					{
						"binary_name": "python3-ansible-runner",
						"binary_version": "2.1.1-1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2021/UBUNTU-CVE-2021-4041.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2021-4041"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2028074"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2021-4041"
		}
	]
}
