{
	"schema_version": "1.6.0",
	"id": "UBUNTU-CVE-2019-18874",
	"modified": "2025-01-13T10:22:02Z",
	"published": "2019-11-12T02:15:00Z",
	"related": [
		"CVE-2019-18874",
		"USN-4204-1"
	],
	"details": "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:16.04:LTS",
				"name": "python-psutil",
				"purl": "pkg:deb/ubuntu/python-psutil@3.4.2-1ubuntu0.1?arch=source&distro=xenial"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.4.2-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"2.2.1-3",
				"3.4.1-1",
				"3.4.2-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-psutil",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-dbg",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-doc",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil",
						"binary_version": "3.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil-dbg",
						"binary_version": "3.4.2-1ubuntu0.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-18874.json"
			}
		},
		{
			"package": {
				"ecosystem": "Ubuntu:18.04:LTS",
				"name": "python-psutil",
				"purl": "pkg:deb/ubuntu/python-psutil@5.4.2-1ubuntu0.1?arch=source&distro=bionic"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.4.2-1ubuntu0.1"
						}
					]
				}
			],
			"versions": [
				"5.0.1-1build2",
				"5.4.1-1",
				"5.4.2-1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python-psutil",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-dbg",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python-psutil-doc",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil",
						"binary_version": "5.4.2-1ubuntu0.1"
					},
					{
						"binary_name": "python3-psutil-dbg",
						"binary_version": "5.4.2-1ubuntu0.1"
					}
				],
				"ubuntu_priority": "medium"
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/cve/2019/UBUNTU-CVE-2019-18874.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2019-18874"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/giampaolo/psutil/pull/1616"
		},
		{
			"type": "REPORT",
			"url": "https://github.com/giampaolo/psutil/pull/1624"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/notices/USN-4204-1"
		},
		{
			"type": "REPORT",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-18874"
		}
	]
}
