{
	"schema_version": "1.6.0",
	"id": "USN-5812-1",
	"modified": "2023-01-19T13:52:19.276979Z",
	"published": "2023-01-19T13:52:19.276979Z",
	"related": [
		"CVE-2021-33503",
		"UBUNTU-CVE-2021-33503"
	],
	"summary": "python-urllib3 vulnerability",
	"details": "It was discovered that urllib3 incorrectly handled certain characters\nin URLs. A remote attacker could possibly use this issue to cause urllib3\nto consume resources, leading to a denial of service.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Ubuntu:20.04:LTS",
				"name": "python-urllib3",
				"purl": "pkg:deb/ubuntu/python-urllib3?arch=src?distro=focal"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.25.8-2ubuntu0.2"
						}
					]
				}
			],
			"versions": [
				"1.24.1-1ubuntu1",
				"1.24.1-1ubuntu2",
				"1.25.8-1",
				"1.25.8-2",
				"1.25.8-2ubuntu0.1"
			],
			"ecosystem_specific": {
				"availability": "No subscription required",
				"binaries": [
					{
						"binary_name": "python3-urllib3",
						"binary_version": "1.25.8-2ubuntu0.2"
					}
				]
			},
			"database_specific": {
				"source": "https://github.com/canonical/ubuntu-security-notices/blob/main/osv/usn/USN-5812-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://ubuntu.com/security/notices/USN-5812-1"
		},
		{
			"type": "REPORT",
			"url": "https://ubuntu.com/security/CVE-2021-33503"
		}
	]
}
